export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const PROJECT_CREATED_START = 'PROJECT_CREATED_START';
export const PROJECT_CREATED_SUCCESS = 'PROJECT_CREATED_SUCCESS';
export const PROJECT_CREATED_FAIL = 'PROJECT_CREATED_FAIL';
export const VERSION_CREATED_SUCCESS = 'VERSION_CREATED_SUCCESS';
export const VERSION_CREATED_FAIL = 'VERSION_CREATED_FAIL';

export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAIL = 'HOME_SUCCESS';

export const UI_SHOW_LOADING = 'UI_SHOW_LOADING';
export const UI_HIDE_LOADING = 'UI_HIDE_LOADING';

export const FETCH_CATEGORYANDPARAMETER_START =
  'FETCH_CATEGORYANDPARAMETER_START';
export const FETCH_CATEGORYANDPARAMETER_SUCCESS =
  'FETCH_CATEGORYANDPARAMETER_SUCCESS';
export const FETCH_CATEGORYANDPARAMETER_FAIL =
  'FETCH_CATEGORYANDPARAMETER_FAIL';

export const FETCH_REVITELEMENT_START = 'FETCH_REVITELEMENT_START';
export const FETCH_REVITELEMENT_SUCCESS = 'FETCH_REVITELEMENT_SUCCESS';
export const FETCH_REVITELEMENT_FAIL = 'FETCH_REVITELEMENT_FAIL';
